//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroAppDomain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableCuidado
    {
        public int VariablesCuidadoId { get; set; }
        public int TipoVariableCuidadoId { get; set; }
        public double ValorCuidado { get; set; }
        public int PlantaId { get; set; }
    
        public virtual Planta Planta { get; set; }
        public virtual TipoVariableCuidado TipoVariableCuidado { get; set; }
    }
}
