//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableAmbiente
    {
        public int VariableAmbienteId { get; set; }
        public int ModuloId { get; set; }
        public int TipoVariableAmbienteId { get; set; }
        public double Valor { get; set; }
        public System.DateTime TimeTag { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual TipoVariableAmbiente TipoVariableAmbiente { get; set; }
    }
}
