//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroAppMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgroAppEntities : DbContext
    {
        public AgroAppEntities()
            : base("name=AgroAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Planta> Planta { get; set; }
        public virtual DbSet<TipoVariableAmbiente> TipoVariableAmbiente { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<VariableAmbiente> VariableAmbiente { get; set; }
        public virtual DbSet<VariablesControl> VariablesControl { get; set; }
        public virtual DbSet<TipoVariableCuidado> TipoVariableCuidado { get; set; }
        public virtual DbSet<VariableCuidado> VariableCuidado { get; set; }
    }
}
