//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariablesControl
    {
        public int VariableControlId { get; set; }
        public int PlantaId { get; set; }
        public int TipoVariableAmbienteId { get; set; }
        public double VariableControl { get; set; }
    
        public virtual Planta Planta { get; set; }
        public virtual TipoVariableAmbiente TipoVariableAmbiente { get; set; }
    }
}
