//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modulo()
        {
            this.VariableAmbiente = new HashSet<VariableAmbiente>();
        }
    
        public int ModuloId { get; set; }
        public Nullable<int> PlantaId { get; set; }
        public Nullable<int> NumeroPlantas { get; set; }
        public Nullable<System.DateTime> FechaSiembra { get; set; }
        public Nullable<int> VariablesAmbienteId { get; set; }
        public Nullable<System.DateTime> FechaEstimadaCosecha { get; set; }
        public Nullable<System.DateTime> FechaRealCosecha { get; set; }
        public Nullable<double> SolucionNutricional { get; set; }
    
        public virtual Planta Planta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VariableAmbiente> VariableAmbiente { get; set; }
    }
}
